### ISSUE TITLE
Cannot install exponent on simulator

### ISSUE THREAD

**Issue by khraibani** [exponentjs/xde#40]
When I first load Exponent an error occur in console:

events.js:141 Uncaught Error: spawn /Applications/Exponent XDE.app/Contents/Frameworks/Exponent XDE Helper.app/Contents/MacOS/Exponent XDE Helper ENOENT

Pressing on "Install Exponent on Simulator" another error in the console:

Problem installing app on simulator: Error: JsonFileError: No value for key path version in JSON object
Error: JsonFileError: No value for key path version in JSON object
    at JsonFileError (/Applications/Exponent XDE.app/Contents/Resources/app/node_modules/@exponent/json-file/index.js:35:10)
    at /Applications/Exponent XDE.app/Contents/Resources/app/node_modules/@exponent/json-file/index.js:74:15
    at run (/Applications/Exponent XDE.app/Contents/Resources/app/node_modules/core-js/modules/es6.promise.js:89:22)
    at /Applications/Exponent XDE.app/Contents/Resources/app/node_modules/core-js/modules/es6.promise.js:102:28
    at flush (/Applications/Exponent XDE.app/Contents/Resources/app/node_modules/core-js/modules/_microtask.js:14:5)
    at doNTCallback0 (node.js:443:9)
    at process._tickCallback (node.js:372:13)(anonymous function) @ SimulatorControls.js:47run @ /Applications/Exponent XDE.app/Contents/Resources/app/node_modules/core-js/modules/es6.promise.js:89(anonymous function) @ /Applications/Exponent XDE.app/Contents/Resources/app/node_modules/core-js/modules/es6.promise.js:102flush @ /Applications/Exponent XDE.app/Contents/Resources/app/node_modules/core-js/modules/_microtask.js:14doNTCallback0 @ node.js:443_tickCallback @ node.js:372

**Comment by jesseruder** [comment]
Looks like the `version` field was missing in package.json. We've added more validation that should give a better error message in this case.
