### ISSUE TITLE
Install error on Ubuntu 15.10 - babel-register.

### ISSUE THREAD

**Issue by ben-denzer** [exponentjs/xde#46]
I have the latest version of Swift and openSDK, and using the Node 5.10.1 - I followed the directions for 'build from source' - am I missing something?

---------------------------------------------------------------------------------

> xde@1.6.0 postinstall /home/ben/xde
> gulp postinstall

[02:14:11] Requiring external module babel-register
module.js:341
    throw err;
    ^

Error: Cannot find module '@exponent/json-file'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (package-tasks.js:3:1)
    at Module._compile (module.js:413:34)
    at loader (/home/ben/xde/node_modules/babel-register/lib/node.js:126:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/ben/xde/node_modules/babel-register/lib/node.js:136:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)

**Comment by ccheever** [comment]
Hi- 

Sorry, we've only tested this software on OS X. I think it will take some work to get it to work on Ubuntu/Linux. It's probably possible to do so, but probably requires editing the code a little bit.

If it can't find `@exponent/json-file`, that's odd-- it's just an npm module, and one that should work on any platform. Did you `npm install` before running?

**Comment by ide** [comment]
Think the json-file issue may have been fixed with https://github.com/exponentjs/xde/commit/b5c4d779b74890d3ba2dbf23fb328ef190cf0063. It had to do with case sensitivity on the file system which is why we didn't catch this on Mac. Sorry about that.

**Comment by ben-denzer** [comment]
You guys are awesome - I haven't really used it yet, but it installed, built, and opened. Who needs testing?

**Comment by ben-denzer** [comment]
1 more thing, weird bug. When I publish for the first time, I get this error on the IOS build but not the Android build. But when I just hit publish a 2nd time it works perfect. As far as I'm concerned this is a non-issue and can be closed. Thanks for your help, and now you know, it works on Ubuntu too!

Publishing...
[10:29:02 PM] <START> request:/main.bundle?dev=false&minify=true&hot=false&platform=ios
[10:29:02 PM] <START> find dependencies
[10:30:47 PM] <END>   find dependencies (104785ms)
Failed to publish package: Invalid JSON returned from API: SyntaxError: Unexpected token <. Response body: <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.9.15</center>
</body>
</html>

**Comment by jesseruder** [comment]
I think this publish issue has been fixed, so closing for now
