### ISSUE TITLE
I'm behind a proxy (socks5). XDE connection timed out.

### ISSUE THREAD

**Issue by GrigoryPtashko** [exponentjs/xde#55]
Hello.

Here's what the XDE is saying:

![screen shot 2016-08-24 at 17 31 47](https://cloud.githubusercontent.com/assets/2768788/17934541/5831afa0-6a29-11e6-936f-f1a387dfecb2.png)

Any chance to get it working through a proxy?

**Comment by ccheever** [comment]
Hmmm...

There probably is, but I don't know enough about networking to be able to
come up with a solution off the top of my head.

One thing you could try is downloading the source and running it from
source:
https://github.com/exponentjs/xde

You could play around with the way it does networking stuff and see if you
could get it working.

You could also try running some kind of tunnel to the various ports XDE
uses, but I'm not sure what the details of that setup would be.

Sorry you are having trouble.
Charlie

**Comment by GrigoryPtashko** [comment]
@ccheever maybe you can give me some starting points in terms of filenames and function names which are used to access remote servers? I can take a look for sure since I'm behind a proxy for the whole day everyday :)

**Comment by GrigoryPtashko** [comment]
Hmm.. Running XDE built from source with v2.5.3 did manage to connect via proxy.
Only the logs of the GUI confuse. Is this ok?

````
macbook@terminalx ~/work/xde (detached*)$ npm start

> @ start /Users/macbook/Documents/work/xde
> gulp build && cross-env XDE_NPM_START=1 electron ./app

[10:59:52] Requiring external module babel-register
[10:59:54] Using gulpfile ~/Documents/work/xde/gulpfile.babel.js
[10:59:54] Starting 'build'...
[10:59:54] Starting 'buildNativeModules'...
[10:59:54] Starting 'babel'...
[10:59:54] Starting 'icon'...
[10:59:54] Finished 'icon' after 557 ms
[10:59:57] Finished 'babel' after 2.98 s
[10:59:57] Finished 'buildNativeModules' after 3.21 s
[10:59:57] Finished 'build' after 3.21 s
Error: Module version mismatch. Expected 49, got 48.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:167:20)
    at Object.Module._extensions..node (module.js:568:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:167:20)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/macbook/Documents/work/xde/app/node_modules/dtrace-provider/dtrace-provider.js:17:23)
{ Error: Cannot find module './build/default/DTraceProviderBindings'
    at Module._resolveFilename (module.js:440:15)
    at Function.Module._resolveFilename (/Users/macbook/Documents/work/xde/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/macbook/Documents/work/xde/app/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/Debug/DTraceProviderBindings'
    at Module._resolveFilename (module.js:440:15)
    at Function.Module._resolveFilename (/Users/macbook/Documents/work/xde/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/macbook/Documents/work/xde/app/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12) code: 'MODULE_NOT_FOUND' }
```

**Comment by ccheever** [comment]
hi @GrigoryPtashko -- 

Hmmm.... I think the native module version mismatches might be because you are running a different version of node from whatever electron was built with. Those errors don't seem to have anything to do with networking.

You might try installed node 6.3 (we recommend using `nvm` to manage node versions) and then `rm -rf`-ing your `node_modules` and then `npm install`ing again.

**Comment by jesseruder** [comment]
Seems like running from source worked. The native module mismatch issue should be fixed now.
