### ISSUE TITLE
Failure creating a new project

### ISSUE THREAD

**Issue by bolinfest** [exponentjs/xde#58]
I get the following error:

```
ValidationError: child "name" fails because ["name" is required]
```

I have a name entered in the box as well as a path in the second field.

**Comment by bolinfest** [comment]
This is using the XDE built from source on Ubuntu at 314bfca8754f69c6f7d5ff3c63a2ab3cc542e63c. I guess I should try the 1.0 tag?

**Comment by bolinfest** [comment]
I just tried running `npm install` with the v1.2.0 branch, but that also failed:

```
npm WARN optional dep failed, continuing fsevents@1.0.14
npm ERR! Linux 3.13.0-57-generic
npm ERR! argv "/home/mbolin/.nvm/versions/node/v4.1.1/bin/node" "/home/mbolin/.nvm/versions/node/v4.1.1/bin/npm" "install"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE

npm ERR! ngrok@0.1.99 postinstall: `node ./postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ngrok@0.1.99 postinstall script 'node ./postinstall.js'.
npm ERR! This is most likely a problem with the ngrok package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./postinstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls ngrok
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mbolin/code/xde/npm-debug.log
```

I'm on Ubuntu 14.04.5.

**Comment by ide** [comment]
Yeah, master gives that error right now. Can you try the v2.6.0 tag, reinstall node modules, and try again?

**Comment by bolinfest** [comment]
@ide OK, thanks, I didn't see the v2.6.0 tag because I was only looking at the branches. I even went so far as to upgrade from Ubuntu 14.04 to 16.04. Now I ran:

```
nvm use v4.1.1
git clean -xfd
npm install
npm start
```

but now I am getting this error:

```
mbolin@stout:~/code/xde$ npm start

> @ start /home/mbolin/code/xde
> gulp build && cross-env XDE_NPM_START=1 electron ./app

[07:33:44] Failed to load external module babel-register
[07:33:44] Failed to load external module babel-core/register
[07:33:44] Failed to load external module babel/register
/home/mbolin/code/xde/gulpfile.babel.js:1
(function (exports, require, module, __filename, __dirname) { import gulp from 'gulp';
                                                              ^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at execute (/home/mbolin/code/xde/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0-alpha.2/index.js:35:18)
    at Liftoff.handleArguments (/home/mbolin/code/xde/node_modules/gulp/node_modules/gulp-cli/index.js:149:63)
    at Liftoff.<anonymous> (/home/mbolin/code/xde/node_modules/gulp/node_modules/gulp-cli/node_modules/liftoff/index.js:198:16)

npm ERR! Linux 4.4.0-36-generic
npm ERR! argv "/home/mbolin/.nvm/versions/node/v4.1.1/bin/node" "/home/mbolin/.nvm/versions/node/v4.1.1/bin/npm" "start"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE
npm ERR! @ start: `gulp build && cross-env XDE_NPM_START=1 electron ./app`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start script 'gulp build && cross-env XDE_NPM_START=1 electron ./app'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build && cross-env XDE_NPM_START=1 electron ./app
npm ERR! You can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mbolin/code/xde/npm-debug.log
```

**Comment by bolinfest** [comment]
I feel like I should give in and use the CLI instead? https://github.com/exponentjs/exp

**Comment by bolinfest** [comment]
Ugh, that doesn't work either:

```
$ exp init .
? Project name: storytime
[exp] Downloading project files...
[exp] Extracting project files...
tar: storytime: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
Process exited with non-zero code: 2
```

**Comment by bolinfest** [comment]
I don't see any tags for `exp`, so I'm on master: `74482b88e2ef191664b31aaec060330c71e62c0c`.

**Comment by bolinfest** [comment]
Hmm, for XDE, I was looking at the wrong version of the `README.md` for install instructions. Looking at https://github.com/exponentjs/xde/tree/v2.6.0, I see I need `nvm install v6`.

**Comment by bolinfest** [comment]
OK, running the installation instructions at https://github.com/exponentjs/xde/tree/v2.6.0 on Ubuntu 16.04 worked for me. I was able to start XDE and create a project. I was able to send myself a link via email on my iPad for the default app and start it up.

**Comment by brentvatne** [comment]
sorry for all of the hassle @bolinfest, glad you were able to resolve it!
