### ISSUE TITLE
XDE install on fedora 24 fails 

### ISSUE THREAD

**Issue by thawkins** [exponentjs/xde#61]
Im trying to install XDE on Fedora 24, I have android Studio installed 

I get all the way through to registing the node packages and get this

```
[thawkins@timdev05 xde]$ npm install .
npm WARN deprecated electron-packager@5.2.1: Critical security bug fixed in v7.0.0 - read more at https://github.com/electron-userland/electron-packager/issues/333

> ngrok@0.1.99 postinstall /home/thawkins/bin/exponent/xde/node_modules/ngrok
> node ./postinstall.js

ngrok - downloading newest binary...
(node:18584) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
ngrok - binary downloaded (https://api.equinox.io/1/Applications/ap_pJSFC5wQYkAyI0FIVwKYs9h1hW/Updates/Asset/ngrok.zip?channel=stable&os=linux&arch=amd64)...
ngrok - error unpacking binary Error: Could not find the End of Central Directory Record
    at DecompressZip.findEndOfDirectory (/home/thawkins/bin/exponent/xde/node_modules/decompress-zip/lib/decompress-zip.js:165:15)
    at _fulfilled (/home/thawkins/bin/exponent/xde/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/thawkins/bin/exponent/xde/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/thawkins/bin/exponent/xde/node_modules/q/q.js:796:13)
    at /home/thawkins/bin/exponent/xde/node_modules/q/q.js:604:44
    at runSingle (/home/thawkins/bin/exponent/xde/node_modules/q/q.js:137:13)
    at flush (/home/thawkins/bin/exponent/xde/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
xde@1.3.4 /home/thawkins/bin/exponent/xde
```
=====================================================================

accessing the url 
https://api.equinox.io/1/Applications/ap_pJSFC5wQYkAyI0FIVwKYs9h1hW/Updates/Asset/ngrok.zip?channel=stable&os=linux&arch=amd64 

produces the following in a browser (chrome)
```
{
"errors": [
{
"message": "Requests to this resource require authentication. No authorization token was present in the request. You must send a valid authorization token in the Authorization header using the Bearer auth. Example: 'Authorization: Bearer {secret}'",
"metadata": {
"authorization-header": ""
}
}
]
}
```
any ideas?

**Comment by jesseruder** [comment]
I'm not sure why it's installing ngrok in the root directory. Do you have ngrok in your xde/package.json?

**Comment by jesseruder** [comment]
We have an AppImage now so you don't need to build from source anymore: https://github.com/exponentjs/xde/releases/tag/v2.9.0
