### ISSUE TITLE
Install fails on previously working project

### ISSUE THREAD

**Issue by benkaiser** [exponentjs/xde#63]
I've moved dev machines and on my clean XDE install, running my app fails.

Link to app source code: https://github.com/benkaiser/summa

Complete log from XDE including failure:
```
00:28:52
Scanning 785 folders for symlinks in /home/benkaiser/HD/GIT/summa/node_modules (20ms)
00:28:52
Running packager on port 19001
00:28:52
Looking for JS files in
   /home/benkaiser/GIT/summa
00:28:53
[12:28:52 am] <START> Building Dependency Graph
00:28:53
[12:28:53 am] <START> Crawling File System
00:28:53
[Hot Module Replacement] Server listening on /hot
00:28:53
React packager ready.
00:28:59
Project opened! You can now use the "Send Link" or "Device" buttons to view your project.
00:29:29
[12:29:29 am] <START> request:/main.bundle?platform=android&dev=true&strict=false&minify=false&hot=false&assetPlugin=exponent/tools/hashAssetFiles&includeAssetFileHashes=true
00:29:29
[12:29:29 am] <START> find dependencies
00:29:30
[12:29:30 am] <END>   Crawling File System (37344ms)
00:29:30
[12:29:30 am] <START> Building in-memory fs for JavaScript
00:29:30
[12:29:30 am] <END>   Building in-memory fs for JavaScript (479ms)
00:29:30
[12:29:30 am] <START> Building in-memory fs for Assets
00:29:31
[12:29:31 am] <END>   Building in-memory fs for Assets (263ms)
00:29:31
[12:29:31 am] <START> Building Haste Map
00:29:31
[12:29:31 am] <START> Building (deprecated) Asset Map
00:29:31
[12:29:31 am] <END>   Building (deprecated) Asset Map (44ms)
00:29:31
[12:29:31 am] <END>   Building Haste Map (394ms)
00:29:31
[12:29:31 am] <END>   Building Dependency Graph (38501ms)
00:29:47
[12:29:47 am] <END>   find dependencies (18519ms)
00:29:47
Error: File /home/benkaiser/HD/GIT/summa/node_modules/react-native/packager/react-packager/src/Resolver/polyfills/prelude_dev.js not found in any of the roots
    at Fastfs._getAndAssertRoot (/home/benkaiser/HD/GIT/summa/node_modules/react-native/packager/react-packager/src/node-haste/fastfs.js:175:21)
    at Fastfs._getFile (/home/benkaiser/HD/GIT/summa/node_modules/react-native/packager/react-packager/src/node-haste/fastfs.js:185:25)
    at Fastfs.readFile (/home/benkaiser/HD/GIT/summa/node_modules/react-native/packager/react-packager/src/node-haste/fastfs.js:97:23)
    at _cache.get (/home/benkaiser/HD/GIT/summa/node_modules/react-native/packager/react-packager/src/node-haste/Module.js:134:49)
    at Cache.get (/home/benkaiser/HD/GIT/summa/node_modules/react-native/packager/react-packager/src/node-haste/Cache/index.js:59:35)
    at Polyfill.read (/home/benkaiser/HD/GIT/summa/node_modules/react-native/packager/react-packager/src/node-haste/Module.js:130:24)
    at Bundler._toModuleTransport (/home/benkaiser/HD/GIT/summa/node_modules/react-native/packager/react-packager/src/Bundler/index.js:582:14)
    at toModuleTransport (/home/benkaiser/HD/GIT/summa/node_modules/react-native/packager/react-packager/src/Bundler/index.js:415:14)
    at Array.map (native)
    at Promise.resolve.then.response (/home/benkaiser/HD/GIT/summa/node_modules/react-native/packager/react-packager/src/Bundler/index.js:435:48)
```

Using nvm with node version being latest v6 `v6.7.0`.

OS: Arch Linux 64bit - all packages up to date

XDE version: `v2.8.0` tag checked out

I tried setting up a brand new blank app and it seemed to work, is anyone able to work out what this error is and why it's only affecting my project and not the blank starter app?

**Comment by jesseruder** [comment]
Can you try deleting node modules and reinstalling?

**Comment by benkaiser** [comment]
I've tried that several times already, for both xde, the xde app folder and the projects node_modules folder.

Later today I might have a crack at incrementally adding parts from my project to the starter one and see if where it breaks.

**Comment by benkaiser** [comment]
Okay I got to the bottom of it.

The difference between my two machines, is that on my laptop, I just have one disk, but on my other machine I have two disks, and so I store my code on one drive but symlink to it from the other drive.

`react-packager` (as seen in those errors above) is having trouble finding that file through the symlink.

The solution in the end, which works fine, and isn't the worst, is to simply open the project from the non-symlinked location inside xde. As such when building it doesn't have to worry about any symlinks and builds successfully.

**Comment by jesseruder** [comment]
Great. Glad you figured it out.
